"""initial schema

Revision ID: 0001_initial_schema
Revises: 
Create Date: 2026-09-28 16:11:20.379202

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0001_initial_schema'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users'))
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)

    op.create_table('companies',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('website', sa.String(length=500), nullable=True),
    sa.Column('industry', sa.String(length=120), nullable=True),
    sa.Column('location', sa.String(length=200), nullable=True),
    sa.Column('contact_person', sa.String(length=120), nullable=True),
    sa.Column('contact_email', sa.String(length=255), nullable=True),
    sa.Column('contact_phone', sa.String(length=40), nullable=True),
    sa.Column('address', sa.String(length=500), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_companies_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_companies')),
    sa.UniqueConstraint('user_id', name=op.f('uq_companies_user_id'))
    )
    op.create_table('company_services',
    sa.Column('company_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('fk_company_services_company_id_companies'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_company_services'))
    )
    with op.batch_alter_table('company_services', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_company_services_company_id'), ['company_id'], unique=False)

    op.create_table('email_configurations',
    sa.Column('company_id', sa.Uuid(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('smtp_host', sa.String(length=255), nullable=False),
    sa.Column('smtp_port', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=255), nullable=False),
    sa.Column('encrypted_password', sa.Text(), nullable=False),
    sa.Column('security_type', sa.Enum('NONE', 'STARTTLS', 'SSL_TLS', name='securitytype', native_enum=False, length=20), nullable=False),
    sa.Column('sender_name', sa.String(length=120), nullable=False),
    sa.Column('reply_to', sa.String(length=255), nullable=True),
    sa.Column('last_tested_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_test_success', sa.Boolean(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('fk_email_configurations_company_id_companies'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_email_configurations')),
    sa.UniqueConstraint('company_id', name=op.f('uq_email_configurations_company_id'))
    )
    op.create_table('email_history',
    sa.Column('company_id', sa.Uuid(), nullable=False),
    sa.Column('sent_by_user_id', sa.Uuid(), nullable=True),
    sa.Column('sender_email', sa.String(length=255), nullable=False),
    sa.Column('sender_name', sa.String(length=120), nullable=True),
    sa.Column('recipient', sa.String(length=255), nullable=False),
    sa.Column('cc', sa.JSON(), nullable=False),
    sa.Column('bcc', sa.JSON(), nullable=False),
    sa.Column('subject', sa.String(length=300), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('email_format', sa.Enum('HTML', 'PLAIN_TEXT', name='emailformat', native_enum=False, length=20), nullable=False),
    sa.Column('status', sa.Enum('SENT', 'FAILED', name='emailstatus', native_enum=False, length=20), nullable=False),
    sa.Column('error_message', sa.String(length=500), nullable=True),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('fk_email_history_company_id_companies'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sent_by_user_id'], ['users.id'], name=op.f('fk_email_history_sent_by_user_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_email_history'))
    )
    with op.batch_alter_table('email_history', schema=None) as batch_op:
        batch_op.create_index('ix_email_history_company_created', ['company_id', 'created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_email_history_status'), ['status'], unique=False)

    op.create_table('email_preferences',
    sa.Column('company_id', sa.Uuid(), nullable=False),
    sa.Column('sender_name', sa.String(length=120), nullable=True),
    sa.Column('reply_to', sa.String(length=255), nullable=True),
    sa.Column('default_format', sa.Enum('HTML', 'PLAIN_TEXT', name='emailformat', native_enum=False, length=20), nullable=False),
    sa.Column('daily_send_limit', sa.Integer(), nullable=False),
    sa.Column('max_recipients_per_email', sa.Integer(), nullable=False),
    sa.Column('max_send_retries', sa.Integer(), nullable=False),
    sa.Column('default_cc', sa.JSON(), nullable=False),
    sa.Column('default_bcc', sa.JSON(), nullable=False),
    sa.Column('extra_settings', sa.JSON(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('fk_email_preferences_company_id_companies'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_email_preferences')),
    sa.UniqueConstraint('company_id', name=op.f('uq_email_preferences_company_id'))
    )
    op.create_table('email_signatures',
    sa.Column('company_id', sa.Uuid(), nullable=False),
    sa.Column('signature_text', sa.Text(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('append_automatically', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('fk_email_signatures_company_id_companies'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_email_signatures')),
    sa.UniqueConstraint('company_id', name=op.f('uq_email_signatures_company_id'))
    )
    op.create_table('social_links',
    sa.Column('company_id', sa.Uuid(), nullable=False),
    sa.Column('platform', sa.String(length=60), nullable=False),
    sa.Column('url', sa.String(length=500), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('fk_social_links_company_id_companies'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_social_links')),
    sa.UniqueConstraint('company_id', 'url', name='uq_social_links_company_url')
    )
    with op.batch_alter_table('social_links', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_social_links_company_id'), ['company_id'], unique=False)

    op.create_table('target_customers',
    sa.Column('company_id', sa.Uuid(), nullable=False),
    sa.Column('segment', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('fk_target_customers_company_id_companies'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_target_customers'))
    )
    with op.batch_alter_table('target_customers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_target_customers_company_id'), ['company_id'], unique=False)

    op.create_table('value_propositions',
    sa.Column('company_id', sa.Uuid(), nullable=False),
    sa.Column('statement', sa.Text(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('fk_value_propositions_company_id_companies'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_value_propositions'))
    )
    with op.batch_alter_table('value_propositions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_value_propositions_company_id'), ['company_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('value_propositions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_value_propositions_company_id'))

    op.drop_table('value_propositions')
    with op.batch_alter_table('target_customers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_target_customers_company_id'))

    op.drop_table('target_customers')
    with op.batch_alter_table('social_links', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_social_links_company_id'))

    op.drop_table('social_links')
    op.drop_table('email_signatures')
    op.drop_table('email_preferences')
    with op.batch_alter_table('email_history', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_email_history_status'))
        batch_op.drop_index('ix_email_history_company_created')

    op.drop_table('email_history')
    op.drop_table('email_configurations')
    with op.batch_alter_table('company_services', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_company_services_company_id'))

    op.drop_table('company_services')
    op.drop_table('companies')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    # ### end Alembic commands ###
